-- UP Cloth Market — PostgreSQL schema for Supabase
-- Created from the MySQL ER schema + chat & notification tables
-- Run this entire file in the Supabase SQL Editor (one execution).

create extension if not exists pgcrypto;

-- ============================================================================
-- USERS (auth.users references) — buyer & seller kept separate per ER
-- ============================================================================

create table public.seller (
    seller_id uuid primary key references auth.users(id) on delete cascade,
    username text not null unique,
    name text not null,
    email text,
    phone text,
    places text
);

create table public.buyer (
    buyer_id uuid primary key references auth.users(id) on delete cascade,
    username text not null unique,
    name text not null,
    email text,
    phone text,
    address text
);

-- ============================================================================
-- PRODUCT
-- ============================================================================

create table public.product (
    product_id int generated by default as identity primary key,
    product_name text not null,
    price numeric(10,2) not null check (price >= 0),
    image text,
    description text,
    category text,
    quantity int not null default 0 check (quantity >= 0),
    size text,
    color text,
    seller_id uuid not null references public.seller(seller_id) on delete cascade
);

-- ============================================================================
-- CART
-- ============================================================================

create table public.cart (
    cart_id uuid primary key default gen_random_uuid(),
    buyer_id uuid not null unique references public.buyer(buyer_id) on delete cascade
);

create table public.cart_item (
    cart_item_id int generated by default as identity primary key,
    quantity int not null check (quantity > 0),
    selected_color text,
    selected_size text,
    cart_id uuid not null references public.cart(cart_id) on delete cascade,
    product_id int not null references public.product(product_id) on delete cascade,
    unique (cart_id, product_id, selected_color, selected_size)
);

-- ============================================================================
-- ORDERS
-- ============================================================================

create table public.orders (
    order_id int generated by default as identity primary key,
    order_date timestamptz not null default now(),
    total_amount numeric(10,2) not null check (total_amount >= 0),
    status text not null default 'Pending' check (status in ('Pending','Paid','Shipped','Delivered')),
    buyer_id uuid not null references public.buyer(buyer_id) on delete cascade
);

create table public.order_item (
    order_item_id int generated by default as identity primary key,
    quantity int not null check (quantity > 0),
    price numeric(10,2) not null check (price >= 0),
    color text,
    size text,
    subtotal numeric(10,2) not null check (subtotal >= 0),
    order_id int not null references public.orders(order_id) on delete cascade,
    product_id int not null references public.product(product_id)
);

-- ============================================================================
-- CHAT
-- ============================================================================

create table public.conversations (
    id uuid primary key default gen_random_uuid(),
    buyer_id uuid not null references public.buyer(buyer_id) on delete cascade,
    seller_id uuid not null references public.seller(seller_id) on delete cascade,
    product_id int references public.product(product_id) on delete set null,
    created_at timestamptz not null default now(),
    unique (buyer_id, seller_id, product_id)
);

create table public.messages (
    id uuid primary key default gen_random_uuid(),
    conversation_id uuid not null references public.conversations(id) on delete cascade,
    sender_id uuid not null references auth.users(id) on delete cascade,
    content text not null,
    sent_at timestamptz not null default now()
);

-- ============================================================================
-- NOTIFICATIONS
-- ============================================================================

create table public.notifications (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references auth.users(id) on delete cascade,
    type text not null,
    title text not null,
    content text,
    is_read boolean not null default false,
    created_at timestamptz not null default now()
);

create index if not exists idx_notifications_user on public.notifications (user_id, is_read);
create index if not exists idx_messages_conv on public.messages (conversation_id);
create index if not exists idx_product_seller on public.product (seller_id);
create index if not exists idx_product_category on public.product (category);


-- ============================================================================
-- NOTIFICATION TRIGGERS (server-side, bypass RLS)
-- ============================================================================

create or replace function public.notify_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    if tg_table_name = 'order_item' then
        insert into public.notifications (user_id, type, title, content)
        select p.seller_id, 'order', 'มีออเดอร์ใหม่',
               'มีคำสั่งซื้อ #' || new.order_id || ' สำหรับสินค้า ' || p.product_name
        from public.product p
        where p.product_id = new.product_id;
        return new;
    elsif tg_table_name = 'orders' and old.status is distinct from new.status then
        insert into public.notifications (user_id, type, title, content)
        values (new.buyer_id, 'order_status',
                'สถานะคำสั่งซื้อ #' || new.order_id || ' อัปเดต',
                'สถานะเปลี่ยนเป็น ' || new.status);
        return new;
    end if;
    return new;
end;
$$;

drop trigger if exists trg_order_item_notify on public.order_item;
create trigger trg_order_item_notify
after insert on public.order_item
for each row execute function public.notify_user();

drop trigger if exists trg_orders_status_notify on public.orders;
create trigger trg_orders_status_notify
after update on public.orders
for each row execute function public.notify_user();


-- ============================================================================
-- ROW LEVEL SECURITY
-- ============================================================================

alter table public.seller enable row level security;
alter table public.buyer enable row level security;
alter table public.product enable row level security;
alter table public.cart enable row level security;
alter table public.cart_item enable row level security;
alter table public.orders enable row level security;
alter table public.order_item enable row level security;
alter table public.conversations enable row level security;
alter table public.messages enable row level security;
alter table public.notifications enable row level security;

-- --- seller ---
create policy "seller read own" on public.seller for select using (auth.uid() = seller_id);
create policy "seller insert own" on public.seller for insert with check (auth.uid() = seller_id);
create policy "seller update own" on public.seller for update using (auth.uid() = seller_id);

-- --- buyer ---
create policy "buyer read own" on public.buyer for select using (auth.uid() = buyer_id);
create policy "buyer insert own" on public.buyer for insert with check (auth.uid() = buyer_id);
create policy "buyer update own" on public.buyer for update using (auth.uid() = buyer_id);

-- --- product: public read, owners manage ---
create policy "product public read" on public.product for select using (true);
create policy "product seller insert" on public.product for insert with check (auth.uid() = seller_id);
create policy "product seller update" on public.product for update using (auth.uid() = seller_id);
create policy "product seller delete" on public.product for delete using (auth.uid() = seller_id);

-- --- cart: owner only ---
create policy "cart owner select" on public.cart for select using (auth.uid() = buyer_id);
create policy "cart owner insert" on public.cart for insert with check (auth.uid() = buyer_id);
create policy "cart owner update" on public.cart for update using (auth.uid() = buyer_id);
create policy "cart owner delete" on public.cart for delete using (auth.uid() = buyer_id);

-- --- cart_item: via owning cart ---
create policy "cart_item select via cart" on public.cart_item for select
  using (exists (select 1 from public.cart c where c.cart_id = cart_item.cart_id and c.buyer_id = auth.uid()));
create policy "cart_item insert via cart" on public.cart_item for insert
  with check (exists (select 1 from public.cart c where c.cart_id = cart_item.cart_id and c.buyer_id = auth.uid()));
create policy "cart_item update via cart" on public.cart_item for update
  using (exists (select 1 from public.cart c where c.cart_id = cart_item.cart_id and c.buyer_id = auth.uid()));
create policy "cart_item delete via cart" on public.cart_item for delete
  using (exists (select 1 from public.cart c where c.cart_id = cart_item.cart_id and c.buyer_id = auth.uid()));

-- --- orders: buyer owns; seller managing own products ---
create policy "orders buyer select" on public.orders for select
  using (auth.uid() = buyer_id);
create policy "orders buyer insert" on public.orders for insert with check (auth.uid() = buyer_id);
create policy "orders seller select" on public.orders for select
  using (exists (select 1 from public.order_item oi
                 join public.product p on p.product_id = oi.product_id
                 where oi.order_id = orders.order_id and p.seller_id = auth.uid()));
create policy "orders seller update status" on public.orders for update
  using (exists (select 1 from public.order_item oi
                 join public.product p on p.product_id = oi.product_id
                 where oi.order_id = orders.order_id and p.seller_id = auth.uid()));

-- --- order_item: buyer via order; seller via product ---
create policy "order_item buyer select" on public.order_item for select
  using (exists (select 1 from public.orders o where o.order_id = order_item.order_id and o.buyer_id = auth.uid()));
create policy "order_item seller select" on public.order_item for select
  using (exists (select 1 from public.product p where p.product_id = order_item.product_id and p.seller_id = auth.uid()));
create policy "order_item buyer insert" on public.order_item for insert
  with check (exists (select 1 from public.orders o where o.order_id = order_item.order_id and o.buyer_id = auth.uid()));

-- --- conversations: participants only ---
create policy "conversation select participant" on public.conversations for select
  using (auth.uid() = buyer_id or auth.uid() = seller_id);
create policy "conversation insert buyer" on public.conversations for insert
  with check (auth.uid() = buyer_id);
create policy "conversation insert seller" on public.conversations for insert
  with check (auth.uid() = seller_id);

-- --- messages: participants of conversation only ---
create policy "message select participant" on public.messages for select
  using (exists (select 1 from public.conversations c
                 where c.id = messages.conversation_id
                 and (c.buyer_id = auth.uid() or c.seller_id = auth.uid())));
create policy "message insert participant" on public.messages for insert
  with check (exists (select 1 from public.conversations c
                      where c.id = messages.conversation_id
                      and (c.buyer_id = auth.uid() or c.seller_id = auth.uid())));

-- --- notifications: owner only ---
create policy "notification owner select" on public.notifications for select
  using (auth.uid() = user_id);
create policy "notification owner update" on public.notifications for update
  using (auth.uid() = user_id);
create policy "notification owner delete" on public.notifications for delete
  using (auth.uid() = user_id);