-- UP Cloth Market — product variants (ตัวเลือกไซส์/สี + สต็อกแยกตามตัวเลือก)
-- Run AFTER 0004_rpc.sql
-- สินค้าเดิมทุกชิ้นจะถูก backfill เป็น variant 1 แถว (ใช้ size/color/quantity เดิม)

-- ============================================================================
-- 1) ตารางตัวเลือกสินค้า
-- ============================================================================

create table if not exists public.product_variant (
    variant_id int generated by default as identity primary key,
    product_id int not null references public.product(product_id) on delete cascade,
    size text not null,
    color text not null,
    quantity int not null default 0 check (quantity >= 0),
    unique (product_id, size, color)
);

create index if not exists idx_product_variant_product on public.product_variant (product_id);

alter table public.product_variant enable row level security;

drop policy if exists "product_variant public read" on public.product_variant;
create policy "product_variant public read" on public.product_variant
    for select using (true);

drop policy if exists "product_variant seller insert" on public.product_variant;
create policy "product_variant seller insert" on public.product_variant
    for insert with check (
        exists (select 1 from public.product p
                where p.product_id = product_variant.product_id
                  and p.seller_id = auth.uid())
    );

drop policy if exists "product_variant seller update" on public.product_variant;
create policy "product_variant seller update" on public.product_variant
    for update
    using (
        exists (select 1 from public.product p
                where p.product_id = product_variant.product_id
                  and p.seller_id = auth.uid())
    )
    with check (
        exists (select 1 from public.product p
                where p.product_id = product_variant.product_id
                  and p.seller_id = auth.uid())
    );

drop policy if exists "product_variant seller delete" on public.product_variant;
create policy "product_variant seller delete" on public.product_variant
    for delete using (
        exists (select 1 from public.product p
                where p.product_id = product_variant.product_id
                  and p.seller_id = auth.uid())
    );

-- ============================================================================
-- 2) backfill: สินค้าเดิมทุกชิ้นได้ variant 1 แถว (รันซ้ำได้ ไม่สร้างซ้ำ)
-- ============================================================================

insert into public.product_variant (product_id, size, color, quantity)
select
    product_id,
    coalesce(nullif(trim(size), ''), 'ไม่ระบุ'),
    coalesce(nullif(trim(color), ''), 'ไม่ระบุ'),
    coalesce(quantity, 0)
from public.product
on conflict (product_id, size, color) do nothing;

-- ============================================================================
-- 3) product.quantity = ผลรวมสต็อกของ variants (trigger รักษายอดให้ตรงเสมอ)
-- ============================================================================

create or replace function public.refresh_product_quantity()
returns trigger
language plpgsql
set search_path = public
as $$
begin
    if TG_OP = 'DELETE' then
        update public.product p
        set quantity = coalesce(
            (select sum(quantity) from public.product_variant v where v.product_id = OLD.product_id), 0)
        where p.product_id = OLD.product_id;
        return OLD;
    else
        update public.product p
        set quantity = coalesce(
            (select sum(quantity) from public.product_variant v where v.product_id = NEW.product_id), 0)
        where p.product_id = NEW.product_id;
        return NEW;
    end if;
end;
$$;

drop trigger if exists trg_refresh_product_quantity on public.product_variant;
create trigger trg_refresh_product_quantity
after insert or update of quantity, product_id or delete on public.product_variant
for each row execute function public.refresh_product_quantity();

-- sync ยอดครั้งเดียวหลัง backfill (สินค้าที่ไม่มี variant คงยอดเดิมไว้)
update public.product p
set quantity = coalesce(
    (select sum(quantity) from public.product_variant v where v.product_id = p.product_id),
    p.quantity
);

-- ============================================================================
-- 4) cart_item / order_item อ้างอิง variant
-- ============================================================================

alter table public.cart_item add column if not exists variant_id int;

do $$
begin
    if not exists (select 1 from pg_constraint where conname = 'cart_item_variant_id_fkey') then
        alter table public.cart_item
            add constraint cart_item_variant_id_fkey
            foreign key (variant_id) references public.product_variant(variant_id)
            on delete cascade;
    end if;
end
$$;

-- ตะกร้าใบเดียวมี variant เดียวได้แค่แถวเดียว (variant_id ที่เป็น null ไม่ชนกัน)
create unique index if not exists uq_cart_item_variant
    on public.cart_item (cart_id, variant_id);

alter table public.order_item add column if not exists variant_id int;

do $$
begin
    if not exists (select 1 from pg_constraint where conname = 'order_item_variant_id_fkey') then
        alter table public.order_item
            add constraint order_item_variant_id_fkey
            foreign key (variant_id) references public.product_variant(variant_id)
            on delete set null;
    end if;
end
$$;

-- ============================================================================
-- 5) place_order รองรับ variant_id (สินค้าเก่าที่ไม่มี variant ยังสั่งได้เหมือนเดิม)
-- ============================================================================

create or replace function public.place_order(p_buyer_id uuid, p_items jsonb)
returns int
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order_id int;
  v_item jsonb;
  v_product record;
  v_variant record;
  v_variant_id int;
  v_qty int;
  v_price numeric;
begin
  insert into public.orders (buyer_id, total_amount, status)
  values (p_buyer_id, 0, 'Pending')
  returning order_id into v_order_id;

  for v_item in select * from jsonb_array_elements(p_items) loop
    v_qty := (v_item->>'quantity')::int;

    select * into v_product
    from public.product
    where product_id = (v_item->>'product_id')::int
    for update;

    if not found then
      raise exception 'ไม่พบสินค้า product %', (v_item->>'product_id');
    end if;

    v_variant_id := case
      when nullif(v_item->>'variant_id', '') is null then null
      else (v_item->>'variant_id')::int
    end;

    if v_variant_id is not null then
      -- เส้นทางใหม่: ตัดสต็อกแยกตามตัวเลือก
      select * into v_variant
      from public.product_variant
      where variant_id = v_variant_id
      for update;

      if not found then
        raise exception 'ไม่พบตัวเลือกสินค้า %', v_variant_id;
      end if;
      if v_variant.product_id <> v_product.product_id then
        raise exception 'ตัวเลือกสินค้าไม่ตรงกับสินค้า';
      end if;
      if v_variant.quantity < v_qty then
        raise exception 'สินค้า "%" (%s/%s) มีสต็อกไม่เพียงพอ',
          v_product.product_name, v_variant.size, v_variant.color;
      end if;

      v_price := v_product.price;

      insert into public.order_item (order_id, product_id, variant_id, quantity, price, color, size, subtotal)
      values (
        v_order_id,
        v_product.product_id,
        v_variant.variant_id,
        v_qty,
        v_price,
        v_variant.color,
        v_variant.size,
        v_qty * v_price
      );

      update public.product_variant
      set quantity = v_variant.quantity - v_qty
      where variant_id = v_variant.variant_id;
      -- trigger trg_refresh_product_quantity จะปรับยอดรวม product.quantity ให้เอง
    else
      -- เส้นทางเดิม: สินค้าที่ไม่มี variant (ข้อมูลเก่า)
      if v_product.quantity < v_qty then
        raise exception 'สินค้า "%" มีสต็อกไม่เพียงพอ', v_product.product_name;
      end if;

      v_price := v_product.price;

      insert into public.order_item (order_id, product_id, quantity, price, color, size, subtotal)
      values (
        v_order_id,
        v_product.product_id,
        v_qty,
        v_price,
        nullif(v_item->>'color', ''),
        nullif(v_item->>'size', ''),
        v_qty * v_price
      );

      update public.product
      set quantity = v_product.quantity - v_qty
      where product_id = v_product.product_id;
    end if;
  end loop;

  update public.orders
  set total_amount = coalesce(
    (select sum(subtotal) from public.order_item where order_id = v_order_id), 0
  )
  where order_id = v_order_id;

  return v_order_id;
end;
$$;

revoke all on function public.place_order(uuid, jsonb) from public;
grant execute on function public.place_order(uuid, jsonb) to authenticated;
